name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prettier Check
        run: npx prettier --check .

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Create Release PR or Release
        uses: stellasoftio/lazy-release-action@40cbbc343f8b7c8efb5c7ae4e7fd9b9584472531 # v0.5.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          end-commit: '2234f6208e0c5f12092b557f9e216b28045da54e'
